### ISSUE TITLE
Add support for CORS to the Hono Adapter for NestJS

### ISSUE THREAD

**Issue by mridang** [uki00a/nestjs-platform-deno#65]
It would be neat to have support for CORS. The method is currently not implemented https://github.com/uki00a/nestjs-platform-deno/blob/main/packages/nestjs-platform-hono/src/hono.adapter.ts#L141 

Hono seems to have a CORS middleware https://hono.dev/docs/middleware/builtin/cors so this should be pluggable.

**Comment by uki00a** [comment]
@mridang Thanks for the feedback! I've released [nestjs-platform-hono@0.2.0](https://github.com/uki00a/nestjs-platform-deno/releases/tag/nestjs-platform-hono%400.2.0) which includes support for CORS, static assets (#66) and the not-found handler (#67)
